import { useEffect, useMemo, useState, type FormEvent } from 'react'
import { ManagementIcon } from './ManagementIcon'
import { adjustMaterialLot, consumeMaterialFifo, registerMaterialLot } from './materials'
import { supabase } from './supabase'
import type { Client, DeliveryNote, MaterialConsumption, MaterialLot, Project, Supplier } from './types'
import { clientDisplayName, formatDate, todayIso } from './utils'

const emptyLot = { producer_lot_number: '', material_name: '', component_a: '', component_b: '', initial_quantity_kits: 1, yield_sqm_per_kit: 280, reference_thickness_cm: 14, entry_date: todayIso(), supplier_id: '', delivery_note_id: '', notes: '' }
const emptyConsumption = { client_id: '', project_id: '', application_date: todayIso(), declared_sqm: 0, reference_thickness_cm: 14, notes: '' }
const emptyAdjustment = { lot_id: '', delta_kits: 0, notes: '' }
type Tab = 'lots' | 'consumptions' | 'stock'

export function ManagementMaterialsPage() {
  const [tab, setTab] = useState<Tab>('lots')
  const [lots, setLots] = useState<MaterialLot[]>([])
  const [consumptions, setConsumptions] = useState<MaterialConsumption[]>([])
  const [clients, setClients] = useState<Client[]>([])
  const [projects, setProjects] = useState<Project[]>([])
  const [suppliers, setSuppliers] = useState<Supplier[]>([])
  const [ddts, setDdts] = useState<DeliveryNote[]>([])
  const [lotForm, setLotForm] = useState({ ...emptyLot })
  const [consumptionForm, setConsumptionForm] = useState({ ...emptyConsumption })
  const [adjustmentForm, setAdjustmentForm] = useState({ ...emptyAdjustment })
  const [lotModal, setLotModal] = useState(false)
  const [consumptionModal, setConsumptionModal] = useState(false)
  const [adjustmentModal, setAdjustmentModal] = useState(false)
  const [loading, setLoading] = useState(true)
  const [saving, setSaving] = useState(false)
  const [error, setError] = useState('')

  const load = async () => {
    const [lotResult, consumptionResult, clientResult, projectResult, supplierResult, ddtResult] = await Promise.all([
      supabase.from('material_lots').select('*, suppliers(company_name, contact_name), delivery_notes(number, delivery_date, file_name, file_path)').order('entry_date'),
      supabase.from('material_consumptions').select('*, clients(company_name, contact_name), projects(code, name), material_consumption_lots(quantity_kits, material_lot_id, material_lots(producer_lot_number))').order('application_date', { ascending: false }),
      supabase.from('clients').select('*').order('company_name').order('contact_name'),
      supabase.from('projects').select('*').order('code'),
      supabase.from('suppliers').select('*').order('company_name').order('contact_name'),
      supabase.from('delivery_notes').select('*').order('delivery_date', { ascending: false }),
    ])
    if (lotResult.error || consumptionResult.error) setError('Impossibile caricare il modulo materiali. Applica la migrazione 20260911_material_kits_and_warranties.sql.')
    else {
      setLots((lotResult.data ?? []).map((item) => ({ ...item, initial_quantity_kits: Number(item.initial_quantity_kits), remaining_quantity_kits: Number(item.remaining_quantity_kits), yield_sqm_per_kit: Number(item.yield_sqm_per_kit), reference_thickness_cm: Number(item.reference_thickness_cm) })) as MaterialLot[])
      setConsumptions((consumptionResult.data ?? []).map((item) => ({ ...item, declared_sqm: Number(item.declared_sqm), kits_consumed: Number(item.kits_consumed), reference_thickness_cm: Number(item.reference_thickness_cm), material_consumption_lots: (item.material_consumption_lots ?? []).map((lot: { quantity_kits: number }) => ({ ...lot, quantity_kits: Number(lot.quantity_kits) })) })) as MaterialConsumption[])
    }
    if (!clientResult.error) setClients((clientResult.data ?? []) as Client[])
    if (!projectResult.error) setProjects((projectResult.data ?? []) as Project[])
    if (!supplierResult.error) setSuppliers((supplierResult.data ?? []) as Supplier[])
    if (!ddtResult.error) setDdts((ddtResult.data ?? []) as DeliveryNote[])
    setLoading(false)
  }

  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer) }, [])
  const availableKits = useMemo(() => lots.reduce((sum, lot) => sum + lot.remaining_quantity_kits, 0), [lots])
  const openConsumption = () => { setConsumptionForm({ ...emptyConsumption, application_date: todayIso() }); setConsumptionModal(true); setError('') }
  const openAdjustment = (lotId = '') => { setAdjustmentForm({ ...emptyAdjustment, lot_id: lotId }); setAdjustmentModal(true); setError('') }

  const saveLot = async (event: FormEvent) => { event.preventDefault(); setSaving(true); setError(''); try { await registerMaterialLot({ producerLotNumber: lotForm.producer_lot_number, materialName: lotForm.material_name, componentA: lotForm.component_a, componentB: lotForm.component_b, quantityKits: Number(lotForm.initial_quantity_kits), yieldSqmPerKit: Number(lotForm.yield_sqm_per_kit), referenceThicknessCm: Number(lotForm.reference_thickness_cm), entryDate: lotForm.entry_date, supplierId: lotForm.supplier_id, deliveryNoteId: lotForm.delivery_note_id, notes: lotForm.notes }); setLotModal(false); await load() } catch (saveError) { setError(saveError instanceof Error ? saveError.message : 'Non è stato possibile registrare il lotto.') } setSaving(false) }
  const saveConsumption = async (event: FormEvent) => { event.preventDefault(); setSaving(true); setError(''); try { await consumeMaterialFifo({ clientId: consumptionForm.client_id, projectId: consumptionForm.project_id, applicationDate: consumptionForm.application_date, declaredSqm: Number(consumptionForm.declared_sqm), referenceThicknessCm: Number(consumptionForm.reference_thickness_cm), notes: consumptionForm.notes }); setConsumptionModal(false); await load() } catch (saveError) { setError(saveError instanceof Error ? saveError.message : 'Non è stato possibile registrare il consumo.') } setSaving(false) }
  const saveAdjustment = async (event: FormEvent) => { event.preventDefault(); setSaving(true); setError(''); try { await adjustMaterialLot(adjustmentForm.lot_id, Number(adjustmentForm.delta_kits), adjustmentForm.notes); setAdjustmentModal(false); await load() } catch (saveError) { setError(saveError instanceof Error ? saveError.message : 'Non è stato possibile aggiornare la scorta.') } setSaving(false) }

  const title = 'Materiali, lotti e scorte'
  return <div className="management-materials-page">
    <div className="management-page-heading"><div><span>Magazzino operativo</span><h1>{title}</h1><p>Kit A+B, lotti, consumi FIFO e rettifiche manuali in un unico spazio.</p></div><div className="document-editor__top-actions">{tab === 'lots' && <button className="management-primary-button" type="button" onClick={() => { setLotForm({ ...emptyLot, entry_date: todayIso() }); setLotModal(true) }}><ManagementIcon name="plus" /> Nuovo lotto</button>}{tab === 'consumptions' && <button className="management-primary-button" type="button" onClick={openConsumption}><ManagementIcon name="plus" /> Registra consumo</button>}{tab === 'stock' && <button className="management-primary-button" type="button" onClick={() => openAdjustment()}><ManagementIcon name="plus" /> Rettifica scorta</button>}</div></div>
    {error && <div className="management-alert management-alert--error">{error}</div>}
    <div className="management-stats"><article><span>Kit disponibili</span><strong>{availableKits.toLocaleString('it-IT', { maximumFractionDigits: 3 })}</strong><ManagementIcon name="warehouse" /></article><article><span>Lotti attivi</span><strong>{lots.filter((lot) => lot.remaining_quantity_kits > 0).length}</strong><ManagementIcon name="dashboard" /></article><article><span>Consumi registrati</span><strong>{consumptions.length}</strong><ManagementIcon name="upload" /></article></div>
    <section className="management-card"><div className="management-tabs management-tabs--card"><button className={tab === 'lots' ? 'is-active' : undefined} onClick={() => setTab('lots')}>Lotti e kit</button><button className={tab === 'consumptions' ? 'is-active' : undefined} onClick={() => setTab('consumptions')}>Consumi FIFO</button><button className={tab === 'stock' ? 'is-active' : undefined} onClick={() => setTab('stock')}>Scorte e rettifiche</button></div>{loading ? <div className="management-empty">Caricamento…</div> : tab === 'lots' ? <LotsTable lots={lots} /> : tab === 'consumptions' ? <ConsumptionTable items={consumptions} /> : <StockTable lots={lots} adjust={openAdjustment} />}</section>
    {lotModal && <Modal title="Nuovo lotto materiale" close={() => setLotModal(false)}><form className="management-form management-form--grid" onSubmit={(event) => void saveLot(event)}><label><span>Numero lotto produttore *</span><input required value={lotForm.producer_lot_number} onChange={(e) => setLotForm((c) => ({ ...c, producer_lot_number: e.target.value }))} /></label><label><span>Materiale *</span><input required value={lotForm.material_name} onChange={(e) => setLotForm((c) => ({ ...c, material_name: e.target.value }))} /></label><label><span>Componente A *</span><input required value={lotForm.component_a} onChange={(e) => setLotForm((c) => ({ ...c, component_a: e.target.value }))} /></label><label><span>Componente B *</span><input required value={lotForm.component_b} onChange={(e) => setLotForm((c) => ({ ...c, component_b: e.target.value }))} /></label><label><span>Quantità iniziale (kit) *</span><input required min="0.000001" step="0.000001" type="number" value={lotForm.initial_quantity_kits} onChange={(e) => setLotForm((c) => ({ ...c, initial_quantity_kits: Number(e.target.value) }))} /></label><label><span>Rendimento (m²/kit) *</span><input required min="0.000001" step="0.001" type="number" value={lotForm.yield_sqm_per_kit} onChange={(e) => setLotForm((c) => ({ ...c, yield_sqm_per_kit: Number(e.target.value) }))} /></label><label><span>Spessore riferimento (cm) *</span><input required min="0.001" step="0.001" type="number" value={lotForm.reference_thickness_cm} onChange={(e) => setLotForm((c) => ({ ...c, reference_thickness_cm: Number(e.target.value) }))} /></label><label><span>Data ingresso *</span><input required type="date" value={lotForm.entry_date} onChange={(e) => setLotForm((c) => ({ ...c, entry_date: e.target.value }))} /></label><label><span>Fornitore *</span><select required value={lotForm.supplier_id} onChange={(e) => setLotForm((c) => ({ ...c, supplier_id: e.target.value }))}><option value="">Seleziona</option>{suppliers.map((item) => <option key={item.id} value={item.id}>{item.company_name || item.contact_name}</option>)}</select></label><label><span>DDT ingresso *</span><select required value={lotForm.delivery_note_id} onChange={(e) => setLotForm((c) => ({ ...c, delivery_note_id: e.target.value }))}><option value="">Seleziona DDT</option>{ddts.map((item) => <option key={item.id} value={item.id}>{item.number} · {formatDate(item.delivery_date)}</option>)}</select></label><label className="is-wide"><span>Note</span><textarea rows={3} value={lotForm.notes} onChange={(e) => setLotForm((c) => ({ ...c, notes: e.target.value }))} /></label><Actions saving={saving} close={() => setLotModal(false)} /></form></Modal>}
    {consumptionModal && <Modal title="Consumo materiale FIFO" close={() => setConsumptionModal(false)}><form className="management-form management-form--grid" onSubmit={(event) => void saveConsumption(event)}><label><span>Cliente *</span><select required value={consumptionForm.client_id} onChange={(e) => setConsumptionForm((c) => ({ ...c, client_id: e.target.value }))}><option value="">Seleziona</option>{clients.map((item) => <option key={item.id} value={item.id}>{clientDisplayName(item)}</option>)}</select></label><label><span>Lavoro / commessa *</span><select required value={consumptionForm.project_id} onChange={(e) => setConsumptionForm((c) => ({ ...c, project_id: e.target.value }))}><option value="">Seleziona</option>{projects.filter((item) => !consumptionForm.client_id || item.client_id === consumptionForm.client_id).map((item) => <option key={item.id} value={item.id}>{item.code} · {item.name}</option>)}</select></label><label><span>Data applicazione *</span><input required type="date" value={consumptionForm.application_date} onChange={(e) => setConsumptionForm((c) => ({ ...c, application_date: e.target.value }))} /></label><label><span>m² dichiarati *</span><input required min="0.001" step="0.001" type="number" value={consumptionForm.declared_sqm || ''} onChange={(e) => setConsumptionForm((c) => ({ ...c, declared_sqm: Number(e.target.value) }))} /></label><label><span>Spessore riferimento (cm) *</span><input required min="0.001" step="0.001" type="number" value={consumptionForm.reference_thickness_cm} onChange={(e) => setConsumptionForm((c) => ({ ...c, reference_thickness_cm: Number(e.target.value) }))} /></label><label className="is-wide"><span>Note</span><textarea rows={3} value={consumptionForm.notes} onChange={(e) => setConsumptionForm((c) => ({ ...c, notes: e.target.value }))} /></label><Actions saving={saving} close={() => setConsumptionModal(false)} /></form></Modal>}
    {adjustmentModal && <Modal title="Rettifica manuale scorta" close={() => setAdjustmentModal(false)}><form className="management-form management-form--grid" onSubmit={(event) => void saveAdjustment(event)}><label className="is-wide"><span>Lotto *</span><select required value={adjustmentForm.lot_id} onChange={(e) => setAdjustmentForm((c) => ({ ...c, lot_id: e.target.value }))}><option value="">Seleziona lotto</option>{lots.map((lot) => <option key={lot.id} value={lot.id}>{lot.producer_lot_number} · residuo {lot.remaining_quantity_kits} kit</option>)}</select></label><label><span>Variazione kit *</span><input required type="number" step="0.000001" value={adjustmentForm.delta_kits || ''} onChange={(e) => setAdjustmentForm((c) => ({ ...c, delta_kits: Number(e.target.value) }))} /></label><label className="is-wide"><span>Motivazione *</span><textarea required rows={3} value={adjustmentForm.notes} onChange={(e) => setAdjustmentForm((c) => ({ ...c, notes: e.target.value }))} /></label><div className="management-alert management-alert--success is-wide">Usa un valore positivo per un carico e negativo per una rettifica in diminuzione. Ogni variazione crea uno storico movimento.</div><Actions saving={saving} close={() => setAdjustmentModal(false)} /></form></Modal>}
  </div>
}

function LotsTable({ lots }: { lots: MaterialLot[] }) { return lots.length ? <div className="management-table-wrap"><table className="management-table"><thead><tr><th>Lotto</th><th>Materiale / componenti</th><th>Ingresso / DDT</th><th>Residuo</th><th>Rendimento</th><th>Stato</th></tr></thead><tbody>{lots.map((lot) => <tr key={lot.id}><td><strong>{lot.producer_lot_number}</strong><small>{lot.suppliers?.company_name || lot.suppliers?.contact_name || '—'}</small></td><td>{lot.material_name}<small>A: {lot.component_a} · B: {lot.component_b}</small></td><td>{formatDate(lot.entry_date)}<small>{lot.delivery_notes?.number || 'DDT non disponibile'}</small></td><td><strong>{lot.remaining_quantity_kits.toLocaleString('it-IT', { maximumFractionDigits: 3 })} kit</strong><small>{(lot.remaining_quantity_kits * lot.yield_sqm_per_kit).toLocaleString('it-IT', { maximumFractionDigits: 1 })} m² teorici</small></td><td>{lot.yield_sqm_per_kit} m²/kit<small>a {lot.reference_thickness_cm} cm</small></td><td><span className={`management-badge status-${lot.status}`}>{lot.status === 'partially_used' ? 'Parzialmente utilizzato' : lot.status === 'exhausted' ? 'Esaurito' : 'Disponibile'}</span></td></tr>)}</tbody></table></div> : <div className="management-empty">Nessun lotto registrato.</div> }
function ConsumptionTable({ items }: { items: MaterialConsumption[] }) { return items.length ? <div className="management-table-wrap"><table className="management-table"><thead><tr><th>Data</th><th>Cliente / lavoro</th><th>Superficie</th><th>Kit</th><th>Lotti FIFO</th></tr></thead><tbody>{items.map((item) => <tr key={item.id}><td>{formatDate(item.application_date)}</td><td><strong>{item.projects?.code || '—'}</strong><small>{item.clients ? clientDisplayName(item.clients) : '—'}</small></td><td>{item.declared_sqm.toLocaleString('it-IT')} m²</td><td>{item.kits_consumed.toLocaleString('it-IT', { maximumFractionDigits: 6 })}</td><td>{item.material_consumption_lots?.map((lot) => `${lot.material_lots?.producer_lot_number || 'lotto'} (${lot.quantity_kits})`).join(', ') || '—'}</td></tr>)}</tbody></table></div> : <div className="management-empty">Nessun consumo registrato.</div> }
function StockTable({ lots, adjust }: { lots: MaterialLot[]; adjust: (lotId: string) => void }) { return lots.length ? <div className="management-table-wrap"><table className="management-table"><thead><tr><th>Lotto</th><th>Materiale</th><th>Disponibile</th><th>Superficie teorica</th><th /></tr></thead><tbody>{lots.map((lot) => <tr key={lot.id}><td><strong>{lot.producer_lot_number}</strong><small>Ingresso {formatDate(lot.entry_date)}</small></td><td>{lot.material_name}</td><td><strong>{lot.remaining_quantity_kits.toLocaleString('it-IT', { maximumFractionDigits: 6 })} kit</strong></td><td>{(lot.remaining_quantity_kits * lot.yield_sqm_per_kit).toLocaleString('it-IT', { maximumFractionDigits: 2 })} m²</td><td><button className="management-secondary-button" type="button" onClick={() => adjust(lot.id)}>Rettifica</button></td></tr>)}</tbody></table></div> : <div className="management-empty">Nessuna scorta disponibile.</div> }
function Modal({ title, close, children }: { title: string; close: () => void; children: React.ReactNode }) { return <div className="management-modal" role="dialog" aria-modal="true"><button className="management-modal__backdrop" type="button" aria-label="Chiudi" onClick={close} /><div className="management-modal__panel management-modal__panel--wide"><div className="management-modal__header"><div><span>Magazzino</span><h2>{title}</h2></div><button type="button" onClick={close} aria-label="Chiudi"><ManagementIcon name="x" /></button></div>{children}</div></div> }
function Actions({ saving, close }: { saving: boolean; close: () => void }) { return <div className="management-form__actions is-wide"><button className="management-secondary-button" type="button" onClick={close}>Annulla</button><button className="management-primary-button" disabled={saving}>{saving ? 'Salvataggio…' : 'Salva'}</button></div> }
